services:
  api:
    build:
      context: .
    ports: 
      - 3001:3001
    depends_on:
      toodoo-db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: toodoo
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
  toodoo-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: toodoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./toodoo-schema.sql:/docker-entrypoint-initdb.d/toodoo.sql